name: Auto build release
on:
  release:
    types: [created]

permissions:
  contents: write
  packages: write

jobs:
  releases-matrix:
    name: Release Go Binary
    runs-on: ubuntu-latest
    strategy:
      matrix:
        goos: [windows, freebsd, openbsd, linux, darwin]
        goarch: [amd64, 386, arm64, arm]
        exclude:
          - goarch: 386
            goos: darwin
          - goarch: arm
            goos: darwin


          - goarch: arm
            goos: windows
          - goarch: 386
            goos: windows

          - goarch: arm
            goos: freebsd
          - goarch: 386
            goos: freebsd

          - goarch: arm
            goos: openbsd
          - goarch: 386
            goos: openbsd

      fail-fast: false

    steps:
      - uses: actions/checkout@v3

      - name: Get version
        id: get_version
        run: echo ::set-output name=VERSION::${GITHUB_REF/refs\/tags\//}

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20.9.0'

      - name: Set version
        run: |
          cd ${GITHUB_WORKSPACE}/web
          sed -i 's/old-version/${{ steps.get_version.outputs.VERSION }}/g' ./src/layout/footer/index.vue
          cd ${GITHUB_WORKSPACE}/server
          sed -i 's/old-version/${{ steps.get_version.outputs.VERSION }}/g' ./constant/index.go

      - name: Set go 1
        uses: actions/setup-go@v4
        with:
          go-version: '1.22.2'

      - name: Set go 2
        run: |
          GOROOT=''
          go env > vm
          while read -r line
          do
          if [[ "$line" =~ ^GOROOT.* ]];then
             GOROOT=$(echo "$line" | cut -d "'" -f2)
             break
          fi
          done < vm
          rm -r vm
          sed -i '/SIGTERM = Signal(0xf)/a\SIGUSR1 = Signal(16)\nSIGUSR2 = Signal(17)\nSIGTSTP = Signal(18)\nSIGSTOP = Signal(19)' ${GOROOT}/src/syscall/types_windows.go
          sed -i '/15: "terminated",/a\16: "SIGUSR1",\n17: "SIGUSR2",\n18: "SIGTSTP",\n19: "SIGSTOP",' ${GOROOT}/src/syscall/types_windows.go
          sed -i '$a\func Kill(...interface{}) error { return nil;}' ${GOROOT}/src/syscall/types_windows.go


      - name: Build web
        run: |
          cd ${GITHUB_WORKSPACE}/web
          npm install
          npm run build
          rm -rf ../server/web/web
          mv web ../server/web/

      - name: Build server
        uses: wangyoucao577/go-release-action@master
        with:
          github_token: ${{ secrets.ACTION_TOKEN }}
          goos: ${{ matrix.goos }}
          goarch: ${{ matrix.goarch }}
          goversion: 1.22.2
          project_path: server
          binary_name: AirGo
          extra_files: LICENSE server/config.yaml
          pre_command: export CGO_ENABLED=0
          build_flags: -trimpath
          ldflags: -s -w
