name: test build release
on:
  workflow_dispatch:

permissions:
  contents: write
  packages: write

jobs:
  releases-matrix:
    name: Release Go Binary
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.22.2'

      - name: Build web
        run: |
          cd ${GITHUB_WORKSPACE}/web
          npm install
          npm run build
          rm -rf ../server/web/web
          mv web ../server/web/

      - name: Build server
        run: |
          go version
          go env
          sed -i '/SIGTERM = Signal(0xf)/a\SIGUSR1 = Signal(16)\nSIGUSR2 = Signal(17)\nSIGTSTP = Signal(18)\nSIGSTOP = Signal(19)' $GOROOT/src/syscall/types_windows.go
          sed -i '/15: "terminated",/a\16: "SIGUSR1",\n17: "SIGUSR2",\n18: "SIGTSTP",\n19: "SIGSTOP",' $GOROOT/src/syscall/types_windows.go
          sed -i '$a\func Kill(...interface{}) error { return nil;}' $GOROOT/src/syscall/types_windows.go

          cd ${GITHUB_WORKSPACE}/server
          CGO_ENABLED=0 GOOS=windows GOARCH=amd64 go build -o AirGo_test
          mkdir release
          cp AirGo_test release/

      - name: Uploading
        uses: actions/upload-artifact@v1
        with:
          name: AirGo_test
          path: server/release
