name: test build release
on:
  workflow_dispatch:

permissions:
  contents: write
  packages: write

jobs:
  releases-matrix:
    name: Release Go Binary
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Build web
        run: |
          cd ${GITHUB_WORKSPACE}/web
          npm install
          npm run build
          rm -rf ../server/web/web
          mv web ../server/web/

      - name: Build server
        run: |
         cd ${GITHUB_WORKSPACE}/server
          go build -o AirGo_test
          mkdir release
          cp AirGo_test release/
          sed -i '/SIGTERM = Signal(0xf)/a\SIGUSR1 = Signal(16)\nSIGUSR2 = Signal(17)\nSIGTSTP = Signal(18)\nSIGSTOP = Signal(19)' /usr/local/go/src/syscall/types_windows.go
          sed -i '/15: "terminated",/a\16: "SIGUSR1",\n17: "SIGUSR2",\n18: "SIGTSTP",\n19: "SIGSTOP",' /usr/local/go/src/syscall/types_windows.go
          sed -i '$a\func Kill(...interface{}) error { return nil;}' /usr/local/go/src/syscall/types_windows.go


      - name: Uploading
        uses: actions/upload-artifact@v1
        with:
          name: AirGo_test
          path: server/release
